language: python
python: 2.7

sudo: false

matrix:
  include:
  - python: "2.6"
    env: TOXENV=py26
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.3"
    env: TOXENV=py33
  - python: "3.4"
    env: TOXENV=py34
  - python: pypy-5.7.1
    env: TOXENV=pypy

install:
  # Install tox and flake8 style checker
  - pip install tox==1.7.2 flake8==2.1.0

script:
  # Run the library through flake8
  - flake8 --exclude=".git,docs" --ignore=E501 .

  # Run the unit test suite
  - tox -e $TOX_ENV --  --cov aerofiles --cov-report term-missing

after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls==0.4.2
  - coveralls

deploy:
  provider: pypi
  user: Tobias.Bieniek
  password:
    secure: nyCow38ZEMiLmdYWnSTAOzigFQSEOwHv0AHMF8dQQd3zTOF0pA128C5L2vIrrAdjlK5mS7yUIojwbuvDyZ9ZFV01LQil9/Cy2kV4NQ4mbPtdHIIyNacBT6TyZtHSRBALswNPdFsM2Ony1SH6bdS/b4CYxm/sU+OuzhsitAETzwU=
  on:
    tags: true
    repo: Turbo87/aerofiles
